# Spring properties
spring:
  application:
     name: account-microservice


# Server configuration
server:
  context-path: /micro
  port: 8080


# Cloudant Configuration
cloudant:
    db: demo-now
    username: fbbda1b4-2806-4807-89eb-2b65d7d03981-bluemix
    password: 1798a011924c228111a0aac30ca7e30f671feca55201cea94b3971e96097ce1e
    url: https://fbbda1b4-2806-4807-89eb-2b65d7d03981-bluemix.cloudant.com/